### ISSUE TITLE
SuperPoll doesn't send values back to client

### ISSUE THREAD

**Issue by esluyter** [esluyter/super-bufrd#17]
```
(
OSCdef(\tr, { |msg| msg.postln }, '/tr');
{
  SuperPair(DC.ar(1000)).poll(trigid:1);
  DC.ar(0);
}.play
)
```
vs. expected behavior:
```
(
OSCdef(\tr, { |msg| msg.postln }, '/tr');
{
  DC.ar(1000).poll(trigid:1);
  DC.ar(0);
}.play
)
```

**Comment by elgiano** [comment]
I see, and I think we should change SuperPoll to use SendReply, so that it can send both components. We could send to /tr as well, I don't think we would break anything by sending more than one arg
