### ISSUE TITLE
Missing SuperPair Class

### ISSUE THREAD

**Issue by elgiano** [esluyter/super-bufrd#3]
Can't find SuperPair anywhere!

**Comment by esluyter** [comment]
Oh goodness -- thank you for trying this out and sorry it's in such a messy state. For the latest version use the superpair branch from this repository (which it sounds like you are) and also you'll need this other repository https://github.com/esluyter/test-double which actually contains SuperPair. The documentation is wildly out of date too, really sorry about that, I will try to clean everything up in the coming days now that I know someone else is actually using it :) Meantime, please ask if you have questions.

**Comment by elgiano** [comment]
great work! it all works! I'll open a couple more issues, maybe I can find time to contribute
